### ISSUE TITLE
List of Ingredients

### ISSUE THREAD

**Issue by Petre4488** [chingu-voyages/v46-tier2-team-15#21]
**__User Story Description__**
As a user, 

I want to see a list of ingredients for each recipe, 

So that i will know if i need any more ingredients 

**Acceptance Criteria:**

Display a list of ingredients for each recipe, including the names and units of measurement.

Ensure that the list is comprehensive and accurately reflects the recipe's ingredients.

**Comment by DrazenDrinic** [comment]
There is a RecipePopUp component where we will be able to see the recipe image, heading, a few useful info, and then all the ingredients needed. I will make it as a list of items with a checkbox in front of it, when the user checks the box the ingredient will have a line through. Can you rename this issue to something like the RecipePopUp component?

Also to be able to create the functionality for this component I need DarshanDev10 to finish the RecipeCard and RecipeList components so the date can be passed to this component.
