### ISSUE TITLE
Landing Page Behavior

### ISSUE THREAD

**Issue by Petre4488** [chingu-voyages/v46-tier2-team-15#24]
**__User Story Description__**
As a user, 

I want to stay on the landing page if no search ingredient has been entered and see an error message, 

So that I will understand that I need to provide search criteria to use the app effectively.

**Acceptance Criteria:**

If no search ingredient has been entered, keep the user on the landing page.

Display an error message or instructional message informing the user to provide search criteria.

**Comment by DrazenDrinic** [comment]
This component will open between the Header and Footer and 
it will be the first page a user sees. 
This page should contain some fancy stuff and 
instructions on how to use the Dish Dive App and 
we can add some random recipes below the instructions.

This page will be replaced with the Search page once a search is done.
