### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by Petre4488** [chingu-voyages/v46-tier2-team-15#31]
**__User Story Description__**
As a Product Owner, 

I want to create an "About" page on our website,

So that users can learn more about our team and understand how to use the app effectively.

**Acceptance Criteria:**

Ensure that users can easily access the "About" page from the navbar. 

Include a clear link or button in the navbar.
**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by fayiz770** [comment]
I want to work on about page
