### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by Petre4488** [chingu-voyages/v46-tier2-team-15#35]
**__User Story Description__**
As a PO, 

I want to see a welcome message displayed on header, 

So that users will know what the page is about

**Acceptance Criteria:**

Provide a good looking welcome header message

Include the app logo

Ensure that the message contain small advices on what the app is about

**Comment by DrazenDrinic** [comment]
To make the app really fast and responsive the Header and the Footer will be always on the top/bottom of the screen and always available as a part of the App component. We will use the React Router only to change the content between the Header and the Footer.

So the LandingPage will be replaced with the SearchPage and the SearchPage can be replaced with the AboutPage or AppTeamPage...
But the Header and the footer are going to be there always, there is no need to load them every time. 

The RecipePopUp page and the AppTeamMember page are going to be pop-up pages floating in front of the whole App.
