### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Petre4488** [chingu-voyages/v46-tier2-team-15#36]
**__User Story Description__**
As a PO, 

I want to see a footer, 

So that users can find our Github repo quickly.

**Acceptance Criteria:**

Implement a footer section at the bottom of every page on the website.

Include a clearly labeled and prominently positioned link or button in the footer that directs users to the website's GitHub repository.

Ensure that the GitHub link is functional and takes users directly to the project's GitHub repository page.

Provide a tooltip or hover effect that indicates the purpose of the GitHub link when users hover over it.

Ensure that the footer design is consistent across all pages of the website, maintaining a cohesive user experience.

**Comment by DrazenDrinic** [comment]
To make the app really fast and responsive the Header and the Footer will be always on the top/bottom of the screen and always available as a part of the App component. We will use the React Router only to change the content between the Header and the Footer.

So the LandingPage will be replaced with the SearchPage and the SearchPage can be replaced with the AboutPage or AppTeamPage...
But the Header and the footer are going to be there always, there is no need to load them every time. 

The RecipePopUp page and the AppTeamMember page are going to be pop-up pages floating in front of the whole App.
